feat: change merch fail warning
acm-uiuc/website pull request #122
Opened 2024-01-30 00:41 UTC by jlevine18

2024-01-30 00:42 UTC, jlevine18 commented
Don't merge this yet, adding other improvements (description support, capacity alerts)

2024-02-02 04:25 UTC, devksingh4 requested changes
See review comments. I would also like to disable the "purchase now" button if no size is selected, or if all sizes are sold out. Otherwise, looks good great work!

2024-02-02 04:25 UTC, devksingh4 commented on src/app/(membership)/merch/page.tsx
> +                disabledKeys={merchList["sizes"].filter(filterSoldOut)}
We should also add a textual indicator (e.g. "Sold out") in addition to disabling the key.

2024-02-02 16:31 UTC, jlevine18 commented on src/app/(membership)/merch/page.tsx
> +                disabledKeys={merchList["sizes"].filter(filterSoldOut)}
changed

2024-02-02 20:52 UTC, devksingh4 approved these changes
lgtm

2024-02-02 20:52 UTC, merged